PROJECT=UDP_Chat

GENERATED_EXECUTABLES=bin/key_code_logger \
                      bin/udp_talk

GENERATED_SOURCES=$(PROJECT_ROOT_SOURCE) \
                  $(HG_STATE_SOURCE)

SCRIPTS=

TEST_OUTPUT=tests/results \
            peers.log

